# Generated by Django 5.0.2 on 2024-03-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_followerscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='avatar',
            field=models.ImageField(default='blank-profile-picture-973460_1280.png', upload_to='avatar'),
        ),
    ]
