# Generated by Django 5.0.2 on 2024-04-01 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='avatar',
        ),
    ]
