# Generated by Django 5.0.2 on 2024-07-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_post_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowersCount2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower2', models.CharField(max_length=100)),
                ('user2', models.CharField(max_length=100)),
            ],
        ),
    ]
