# Generated by Django 5.0.2 on 2024-08-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
