# Generated by Django 5.0.2 on 2024-08-20 14:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile_User',
            new_name='Profile_Users',
        ),
    ]
