# Generated by Django 5.0.2 on 2024-08-25 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_profile_users_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commenter_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.profile_user'),
        ),
    ]
