# Generated by Django 5.0.2 on 2024-08-25 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_comments_commenter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commenter_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.profile_user'),
        ),
    ]
